### ISSUE TITLE
Feiertage/Ferien von Österreich 

### ISSUE THREAD

**Issue by australien340** [iobroker-community-adapters/ioBroker.feiertage#147]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by australien340** [comment]
Gibt es eine Möglichkeit, bzw wird so etwas geplant, die Feiertage/Ferien von Österreich einzubinden?

**Comment by Pix---** [comment]
Ich habe die Betreuung des Adapters an die Community abgegeben. Das Einpflegen von Feiertagen ist allerdings nicht so eine große Sache. Wichtig ist nur, dass alle benötigten Daten zur Verfügung stehen.

Die Datei, die die Datei [holidays.js](https://github.com/iobroker-community-adapters/ioBroker.feiertage/blob/master/admin/holidays.js) enthält diese Daten.

Einige Feiertage aus der Schweiz und Italien wurden bereits eingebunden. 

Wenn du einen oder mehrere **Feiertage vorschlagen** willst, die es nur in Österreich gibt, füge die benötigten Daten hinzu.

-  Name
-  Land (in diesem Fall NUR Österreich)
-  Typ (z.B. religiöser Feiertag)
-  Datum (wenn immer am gleichen Datum zB. 1.5. Tag der Arbeit [DE])
-  Wenn kein Datum, wie wird das Datum bestimmt (1. Sonntag im April etc.)

Es gibt für an ein Datum fest gebundene Feiertage noch die Möglichkeit, Brückentage zu definieren. Wenn der Feiertag z.B. immer donnerstags ist (Christi Himmelfahrt), kann der Freitag als Brückentag gewählt werden. Sollte es einen festen Feiertag am Dienstag geben, ließe sich der vorige Montag genauso als Brückentag eintragen. Dies muss noch manuell erfolgen.

**Schulferien werden von diesem Adapter nicht berücksichtigt.**
Der Feiertag Adapter liefert in drei Boolean-Datenpunkten `heute` `morgen`und `übermorgen` Auskunft, ob es sich jeweils um einen Feiertag handelt. Die Ferien können z.B. aus dem [iobroker.schoolfree](https://forum.iobroker.net/topic/22373/aufruf-adapter-iobroker-schoolfree-schulferien) Adapter gelesen werden. Mit einem Skript können die Daten beider Adapter auf einen eigenen Datenpunkt synchronisiert werden.

**Vorschlag für Entwickler**
Die Eintragung eigener persönlicher Feiertage über die Adaptereinstellungen wäre eine gute Weiterentwicklung. Je nach Anwendung des Adapters innerhalb der Hausautomation kann die Anzeige nur persönlich geltender Feiertage Sinn machen.

**Comment by mcm1957** [comment]
Österreichische Feiertage scheinen vollständig enthalten zu sein.
SChulferien werden von diesem Adapter nicht unterstützt.
