### ISSUE TITLE
31.07.2023 is not Nationalfeiertag in der Schweiz

### ISSUE THREAD

**Issue by stef1725** [iobroker-community-adapters/ioBroker.feiertage#164]
**Describe the bug**  
Bei mir wird aktuell der 31.07.2023 als Nationalfeiertag der Schweiz als Feiertag angegeben.

{
  "_id": "feiertage.0.heute.Name",
  "type": "state",
  "common": {
    "name": "Feiertag heute - Name",
    "desc": "Welcher Feiertag ist heute?",
    "type": "string",
    "read": true,
    "write": false
  },
  "native": {},
  "from": "system.adapter.feiertage.0",
  "ts": 1690818687012,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "user": "system.user.admin"
}

Nationalfeiertag in der Schweiz

Richtig währe der 01.08.2023. Wie kann das korrigiert werden?
Danke für die Rückmeldung

**Comment by mcm1957** [comment]
fixed at upcoming 1.1.1
