### ISSUE TITLE
Sprachsauswahl einfügen

### ISSUE THREAD

**Issue by ihavenonick** [iobroker-community-adapters/ioBroker.feiertage#44]
Also der Adapter macht was er soll. Mich stört eigentlich nur die doppelte Aufführung der DPs in deutsch und englisch. Könnte man das mit einer Sprachauswahl begrenzen?

**Comment by Pix---** [comment]
Die Sprachvarianten sind ein Überbleibsel aus der Entwicklung des Adapters. Ich behaupte mal, ein Adapter für deutsche Feiertage brauche keine andere Übersetzung als vielleicht englisch. 
Die Dp stören mich eigentlich nicht. Man kann natürlich im Adapter beim Installieren auf die Systemsprache prüfen und entsprechend den Pfad anlegen, viel Aufwand. 

Ich will jetzt aber nach rund drei Jahren nicht den Pfad ändern. Viele haben den Adapter in Vis oder sogar die Dp in andere Adapter integriert. Das würde nur verwirren. 

Sollte mal aus technischen Gründen eine Neuprogrammierung notwendig sein, würde ich das umsetzen. 
PR sind aber natürlich willkommen. 

Pix


<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ihavenonick** [comment]
Ich schaffe es nicht ein PR zu öffnen, lande beim Klick auf "new PullRequest" immer auf compare.

Kannst das bitte zu den PR verschieben? Mir würden eigentlich auch nur die deutschen DPs reichen, alternativ ne Möglichkeit die englischen ein oder auszublenden.

**Comment by Pix---** [comment]
Habe mich entschieden, die englischen Datenpunkte drin zu lassen. Es gibt zu viele andere Adapter und Skripte, die bereits auf die Datenpunkte dieses Adapters zugreifen. Eine Änderung der Baumstruktur mit den Uuntermenüs /de/ oder /en/ würde einen Rattenschwanz an Änderungen nach sich ziehen.

**Comment by ihavenonick** [comment]
Na von entfernen war auch nicht die Rede. Eine Einstellmöglichkeit welche der beiden man möchte wäre doch ohne Rattenschwanz machbar.

**Comment by Pix---** [comment]
Wenn man eine Sprache möchte und die andere nicht, wird eine entfernt. So könnten Abfragen von zB dem Heizungsadapter und Leere laufen. Deshalb gibt es keine Auswahlmöglichkeit. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ihavenonick** [comment]
OK, Du bist hier der Boss :-)
