### ISSUE TITLE
Version 1.0.15 lässt sich nicht installieren und Bug in 1.0..14

### ISSUE THREAD

**Issue by ihavenonick** [iobroker-community-adapters/ioBroker.feiertage#49]
Ich hatte die 1.0.13 drauf und dort die Einstellungen gesichert.
Ein Update wir auf 1.0.15 angeboten, installiert wird aber 1.0.14 und dort kann man zwar die Einstellungen wieder herstellen, werden aber nicht dauerhaft gespeichert.

$ ./iobroker upgrade feiertage
Update feiertage from @1.0.14 to @1.0.15
NPM version: 6.13.4
npm install iobroker.feiertage@1.0.15 --loglevel error --prefix "/opt/iobroker" (System call)
upload [4] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/words.js words.js application/javascript
upload [3] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/index_m.html index_m.html text/html
upload [2] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/index.html index.html text/html
upload [1] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/holidays.js holidays.js application/javascript
upload [0] feiertage.admin /opt/iobroker/node_modules/iobroker.feiertage/admin/feiertage.png feiertage.png image/png
Adapter "feiertage" updated
process exited with code 0

![grafik](https://user-images.githubusercontent.com/36501310/72908936-852bf400-3d36-11ea-8b84-fb6bd411dd33.png)

**Comment by guergen1** [comment]
Dasselbe hier, aber von 14 zu 15

**Comment by ihavenonick** [comment]
Ist egal von wo, selbst ne Neuinstallation bringt nur die 14.

**Comment by Pix---** [comment]
Fehler gefunden, habe an einer Stelle im Code noch 1.0.14 statt 1.0.15 stehen gehabt. 
Werde dass nun korrigieren und daher wieder eine neue Version 1.0.16 rausgeben.
Danke fürs Melden.

**Comment by Kampfratte** [comment]
@Pix---  denkst du bitte daran, in der main.js das eine wort ein zu fügen, was ich dir im pull request geschickt habe?, da ich das Sylvester leider vergessen hatte :(

**Comment by ihavenonick** [comment]
Und daran, dass mir ein Einstellungsrestore immer noch die ganzen Einstellungen zurücksetzt und somit exakt das Gegenteil macht was es soll? Also auch bei Version 1.0.17.

**Comment by Pix---** [comment]
@ihavenonick Kann diesen Fehler nicht reproduzieren. 
Einstellungen sind bei jedem Update übernommen worden. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ihavenonick** [comment]
Beim Update schon, nur sichere die mal und spiel sie zurück, dann ist alles weg.

**Comment by GermanBluefox** [comment]
Must be fixed now
