### ISSUE TITLE
Idee zur Auswahl der regionalen Feiertage

### ISSUE THREAD

**Issue by Alex0176** [iobroker-community-adapters/ioBroker.feiertage#62]
Hallo,

da es nicht einfach möglich ist, Feiertage händisch zu definieren, wäre eine zentrale Datenbank praktisch, wo man Regionen pflegen kann. 

Ein Feiertag ist ja nicht bei jedem gleich bzw. gibt es für Angestellte im Öffentlichen Dienst bzw. oft auch in Banken mehr Feiertage als für das ,,normale" Volk. 

Dann gibt es noch die Unterschiede bei den Schulferien, die sich je nach Land und Bundesland und teilweise Schule (Schulautonome Tage) verändern. 

Ich würde das hier mal als Ideensammlung starten und vielleicht hat noch jemand etwas Input zu dem Thema an das ich nicht gedacht habe. Für alle ,,gläubigen" sieht die Situation dann auch wieder geringfügig anders aus.... 

lg 

Alex

**Comment by Pix---** [comment]
Hallo Alex,

wie auch schon an anderer Stelle erwähnt, ist die ursprüngliche Intention des Adapters anzuzeigen, ob in Deutschland heute ein Feiertag ist. Es geht ursprünglich um gesetzliche Feiertage, die in den unterschiedlichen Bundesländern auch verschieden viele kirchliche Feiertage einschließen.

Die "freien" Tage eines Lehrers, Soldaten, Kinderarztes, Einzelhändlers (übrigens: die weibliche Form ist immer mit gemeint), ...  sind nicht vom Adapter abzubilden.

Die "Datenbank", also die Berechnung der Feiertage, liegt [[hier](https://github.com/Pix---/ioBroker.feiertage/blob/e08f483d084bf0edb72e285a0ac8668f0aef7018/admin/holidays.js#L3)]. Es gibt Tage, die immer am gleichen Datum stattfinden und es gibt vor allem kirchliche Feiertage, die vom Mond abhängen. Diese müssen berechnet werden und das passiert bei Ausführung.

Es gibt weitere Adapter, wie den iobroker.schoolfree oder auch den sehr nützlichen Javascript-Befehl schedule().
Ich empfehle, einen eigenen Datenpunkt (zB datenpunkt.0.eigenerFeiertag) anzulegen und dessen Zustand mit dem Feiertagsadapter zu synchronisieren. Dann kann man mit eigenen schedules und schoolfree Abfragen weiter präzisieren.

Gruß
Pix
