### ISSUE TITLE
Datum falsch/um einen Tag verschoben

### ISSUE THREAD

**Issue by Grmlrckr** [iobroker-community-adapters/ioBroker.feiertage#63]
Hallo,
ich habe gerade zufällig entdeckt, dass (min.) eine Datumsserie nächstes Jahr falsch ist. Evtl. auch mehrere weitere Daten, aber ich habe gerade eine weitere Instanz nur wg. eines bestimmten Termins angelegt. Deshalb fiel mir das ins Auge.

Und zwar werden alle Adventssonntage 2022 auf den jeweils folgenden Montag gesetzt. Sprich der 1. Advent wäre angeblich der 28.11., Montag etc. 
Auch der Rosenmontag fällt lt. Adapter auf den 15.02. (Dienstag).

![image](https://user-images.githubusercontent.com/35227463/145993284-a61295bc-8503-442e-a7b7-b6eb2b0e603e.png)

Weitere habe ich nicht getestet.

**Comment by Pix---** [comment]
Hallo,

danke für den Hinweis. Ich habe heute ebenfalls Tests gemacht und festgestellt, dass der Adapter die Daten mit Basis des laufenden Jahres berechnet. Rosenmontag 2021 war am 15.2., Rosenmontag 2022 ist am 28.2., der Adapter sagt den Rosenmontag im kommenden Jahr 2022 aber für den 15.2. voraus. Er prüft nicht, ob das Datum in diesem Jahr bereits vergangen ist, um dann die für das nächste Jahr zu berechnen.

Es wundert mich, dass der Fehler erst jetzt erkannt wurde. Letztlich sollte der Adapter aber auch nur prüfen, ob *heute* ein Feiertag ist (heute ist immer das aktuelle Jahr).

Ich arbeite dran.

**Comment by GermanBluefox** [comment]
Please test 1.1.0
